# These are supported funding model platforms

github: mchiasson
patreon: mattchiasson
custom: https://flattr.com/@mattchiasson
custom: https://liberapay.com/MattChiasson/donate
custom: https://www.buymeacoffee.com/MYO5mfJhL
